import { PrismaClient } from "@prisma/client";
const prisma = new PrismaClient();

function normalizeName(raw: string): string {
  const trimmed = raw.trim();
  if (!trimmed) return "";
  const lower = trimmed.toLowerCase();
  return lower.charAt(0).toUpperCase() + lower.slice(1);
}

async function main() {
  console.log("Starting voter registry seed...");

  // Part 1: Students 1-50
  const voters1 = [
    { regNo: "220715T", firstName: "daksitha", lastName: "wijerathne", email: "daksithaw.23@cse.mrt.ac.lk" },
    { regNo: "230002N", firstName: "Abaiyan", lastName: "Ramanaish", email: "abaiyanr.23@cse.mrt.ac.lk" },
    { regNo: "230010L", firstName: "Kalana", lastName: "Abeysundara", email: "kalanaa.23@cse.mrt.ac.lk" },
    { regNo: "230011P", firstName: "Senuth", lastName: "Abeywardana", email: "senutha.23@cse.mrt.ac.lk" },
    { regNo: "230015G", firstName: "Ajey", lastName: "Francis", email: "ajeyf.23@cse.mrt.ac.lk" },
    { regNo: "230021V", firstName: "Yusri", lastName: "Ahamed", email: "yusria.23@cse.mrt.ac.lk" },
    { regNo: "230022B", firstName: "Hamthan", lastName: "Ahamed", email: "hamthana.23@cse.mrt.ac.lk" },
    { regNo: "230023E", firstName: "Sabith", lastName: "Ahamed", email: "sabitha.23@cse.mrt.ac.lk" },
    { regNo: "230025L", firstName: "Asfi", lastName: "Ahamed", email: "asfia.23@cse.mrt.ac.lk" },
    { regNo: "230027U", firstName: "RUZAINI", lastName: "AHMEDH", email: "ruzainia.23@cse.mrt.ac.lk" },
    { regNo: "230029D", firstName: "Yasiru", lastName: "Aluthge", email: "yasirua.23@cse.mrt.ac.lk" },
    { regNo: "230030X", firstName: "Amana", lastName: "Faizal", email: "amanaf.23@cse.mrt.ac.lk" },
    { regNo: "230031C", firstName: "Kusal", lastName: "Amantha", email: "kusala.23@cse.mrt.ac.lk" },
    { regNo: "230042K", firstName: "Nawoda", lastName: "Andrahennadi", email: "nawodaa.23@cse.mrt.ac.lk" },
    { regNo: "230043N", firstName: "Thilokya", lastName: "Angeesa", email: "thilokyaa.23@cse.mrt.ac.lk" },
    { regNo: "230048J", firstName: "Anusan", lastName: "Krishnathas", email: "anusank.23@cse.mrt.ac.lk" },
    { regNo: "230060M", firstName: "ASMA", lastName: "RAUFF", email: "asmar.23@cse.mrt.ac.lk" },
    { regNo: "230062V", firstName: "Rashmika", lastName: "Aththanayake", email: "rashmikaa.23@cse.mrt.ac.lk" },
    { regNo: "230064E", firstName: "Dilsha", lastName: "Atugedara", email: "dilshaa.23@cse.mrt.ac.lk" },
    { regNo: "230069A", firstName: "Ishan", lastName: "Balasooriya", email: "ishanb.23@cse.mrt.ac.lk" },
    { regNo: "230075M", firstName: "gishan", lastName: "bandara", email: "gishanb.23@cse.mrt.ac.lk" },
    { regNo: "230076R", firstName: "Yasiru", lastName: "Bandara", email: "yasirub.23@cse.mrt.ac.lk" },
    { regNo: "230078B", firstName: "Malindu", lastName: "Bandara", email: "malindub.23@cse.mrt.ac.lk" },
    { regNo: "230081D", firstName: "Nirmal", lastName: "Bandara", email: "nirmalb.23@cse.mrt.ac.lk" },
    { regNo: "230089J", firstName: "Kisaja", lastName: "Beddawala", email: "kisajab.23@cse.mrt.ac.lk" },
    { regNo: "230090E", firstName: "Nethmi", lastName: "Bhagya", email: "nethmib.23@cse.mrt.ac.lk" },
    { regNo: "230091H", firstName: "Birajith", lastName: "Kiritharajah", email: "birajithk.23@cse.mrt.ac.lk" },
    { regNo: "230094U", firstName: "Gimsara", lastName: "Bulagala", email: "gimsarab.23@cse.mrt.ac.lk" },
    { regNo: "230101R", firstName: "Dilusha", lastName: "Chandrasiri", email: "dilushac.23@cse.mrt.ac.lk" },
    { regNo: "230102V", firstName: "Jaindu", lastName: "Charindith", email: "jainduc.23@cse.mrt.ac.lk" },
    { regNo: "230104E", firstName: "Rumesh", lastName: "Chathuranga", email: "rumeshc.23@cse.mrt.ac.lk" },
    { regNo: "230111X", firstName: "Maheesha", lastName: "Dabarera", email: "maheeshad.23@cse.mrt.ac.lk" },
    { regNo: "230112C", firstName: "Haren", lastName: "Daishika", email: "harend.23@cse.mrt.ac.lk" },
    { regNo: "230123K", firstName: "Praveen", lastName: "De Silva", email: "praveend.23@cse.mrt.ac.lk" },
    { regNo: "230126X", firstName: "Nimsika", lastName: "Bosilu", email: "nimsikab.23@cse.mrt.ac.lk" },
    { regNo: "230134U", firstName: "Thashira", lastName: "Devindu", email: "thashirad.23@cse.mrt.ac.lk" },
    { regNo: "230135A", firstName: "VIDUSHI", lastName: "DEWDUNIKA", email: "vidushid.23@cse.mrt.ac.lk" },
    { regNo: "230137G", firstName: "Keshana", lastName: "Dewranga", email: "keshanad.23@cse.mrt.ac.lk" },
    { regNo: "230139N", firstName: "HIMATH", lastName: "Dhanapala", email: "himathd.23@cse.mrt.ac.lk" },
    { regNo: "230143V", firstName: "Hasini", lastName: "Dikkumbura", email: "hasinid.23@cse.mrt.ac.lk" },
    { regNo: "230146H", firstName: "chandupa", lastName: "dilhana", email: "chandupad.23@cse.mrt.ac.lk" },
    { regNo: "230150N", firstName: "Lahiru", lastName: "Dilshan", email: "lahirud.23@cse.mrt.ac.lk" },
    { regNo: "230151T", firstName: "Senindu", lastName: "Dinapura", email: "senindud.23@cse.mrt.ac.lk" },
    { regNo: "230152X", firstName: "Suhas", lastName: "Disanayaka", email: "suhasd.23@cse.mrt.ac.lk" },
    { regNo: "230153C", firstName: "Tharindu", lastName: "Disanayaka", email: "tharindud.23@cse.mrt.ac.lk" },
    { regNo: "230165N", firstName: "Yasindu", lastName: "Dissanayake", email: "yasindud.23@cse.mrt.ac.lk" },
    { regNo: "230166T", firstName: "sandali", lastName: "divyangi", email: "sandalid.23@cse.mrt.ac.lk" },
    { regNo: "230168C", firstName: "thilaksan", lastName: "elango", email: "thilaksane.23@cse.mrt.ac.lk" },
    { regNo: "230169F", firstName: "Chirana", lastName: "Edirisinghe", email: "chiranae.23@cse.mrt.ac.lk" },
    { regNo: "230170B", firstName: "Thisen", lastName: "Ekanayake", email: "thisene.23@cse.mrt.ac.lk" },
  ];

  // Part 2: Students 51-100
  const voters2 = [
    { regNo: "230179K", firstName: "Sahanya", lastName: "Fernando", email: "sahanyaf.23@cse.mrt.ac.lk" },
    { regNo: "230181J", firstName: "Dhinanjaya", lastName: "Fernando", email: "dhinanjayaf.23@cse.mrt.ac.lk" },
    { regNo: "230185B", firstName: "Senadi", lastName: "Fernando", email: "senadif.23@cse.mrt.ac.lk" },
    { regNo: "230187H", firstName: "Sheneth", lastName: "Fernando", email: "shenethf.23@cse.mrt.ac.lk" },
    { regNo: "230188L", firstName: "Thevindu", lastName: "Fernando", email: "thevinduf.23@cse.mrt.ac.lk" },
    { regNo: "230190K", firstName: "Gnanasekaran", lastName: "Janushikha", email: "gnanasekaranj.23@cse.mrt.ac.lk" },
    { regNo: "230194C", firstName: "Tharumini", lastName: "Gamage", email: "tharuminig.23@cse.mrt.ac.lk" },
    { regNo: "230196J", firstName: "Idusha", lastName: "Garavi", email: "idushag.23@cse.mrt.ac.lk" },
    { regNo: "230199V", firstName: "Nalina", lastName: "Genkeswaran", email: "nalinag.23@cse.mrt.ac.lk" },
    { regNo: "230201A", firstName: "Chethana", lastName: "Gimhan", email: "chethanag.23@cse.mrt.ac.lk" },
    { regNo: "230202D", firstName: "Dinura", lastName: "Ginige", email: "dinurag.23@cse.mrt.ac.lk" },
    { regNo: "230207X", firstName: "Bavindu", lastName: "Gunasekara", email: "bavindug.23@cse.mrt.ac.lk" },
    { regNo: "230214P", firstName: "Muditha", lastName: "Gunathilaka", email: "mudithag.23@cse.mrt.ac.lk" },
    { regNo: "230219K", firstName: "Harshana", lastName: "Gunawardena", email: "harshanag.23@cse.mrt.ac.lk" },
    { regNo: "230221J", firstName: "Nethsith", lastName: "Gunaweera", email: "nethsithg.23@cse.mrt.ac.lk" },
    { regNo: "230222M", firstName: "Chanupa", lastName: "Gurusinghe", email: "chanupag.23@cse.mrt.ac.lk" },
    { regNo: "230230K", firstName: "Nisal", lastName: "Wilochana", email: "nisalw.23@cse.mrt.ac.lk" },
    { regNo: "230234C", firstName: "Hatheem", lastName: "Rafeek", email: "hatheemr.23@cse.mrt.ac.lk" },
    { regNo: "230242A", firstName: "Muditha", lastName: "Herath", email: "mudithah.23@cse.mrt.ac.lk" },
    { regNo: "230243D", firstName: "Maneesha", lastName: "Herath", email: "maneeshah.23@cse.mrt.ac.lk" },
    { regNo: "230244G", firstName: "Binara", lastName: "Herath", email: "binarah.23@cse.mrt.ac.lk" },
    { regNo: "230246N", firstName: "Yasith", lastName: "Hewarathna", email: "yasithh.23@cse.mrt.ac.lk" },
    { regNo: "230247T", firstName: "Shaluka", lastName: "Theshan", email: "shalukat.23@cse.mrt.ac.lk" },
    { regNo: "230253H", firstName: "Ifaz", lastName: "Ikram", email: "ifazi.23@cse.mrt.ac.lk" },
    { regNo: "230257A", firstName: "Muhammadu", lastName: "Ilham", email: "muhammadui.23@cse.mrt.ac.lk" },
    { regNo: "230263M", firstName: "izzath", lastName: "nisfer", email: "izzathn.23@cse.mrt.ac.lk" },
    { regNo: "230272N", firstName: "Nadeesha", lastName: "Jayamanne", email: "nadeeshaj.23@cse.mrt.ac.lk" },
    { regNo: "230277J", firstName: "Upeksha", lastName: "Jayasekara", email: "upekshaj.23@cse.mrt.ac.lk" },
    { regNo: "230278M", firstName: "Tharaka", lastName: "Jayasena", email: "tharakaj.23@cse.mrt.ac.lk" },
    { regNo: "230279R", firstName: "Thisuri", lastName: "Jayasinghe", email: "thisurij.23@cse.mrt.ac.lk" },
    { regNo: "230281P", firstName: "Damindu", lastName: "Jayasinghe", email: "daminduj.23@cse.mrt.ac.lk" },
    { regNo: "230283A", firstName: "Yohan", lastName: "Jayasinghe", email: "yohanj.23@cse.mrt.ac.lk" },
    { regNo: "230286K", firstName: "SHERON", lastName: "JAYASINGHE", email: "sheronj.23@cse.mrt.ac.lk" },
    { regNo: "230288T", firstName: "Umaya", lastName: "Jayasuriya", email: "umayaj.23@cse.mrt.ac.lk" },
    { regNo: "230291V", firstName: "Kalhara", lastName: "Jayathissa", email: "kalharaj.23@cse.mrt.ac.lk" },
    { regNo: "230295L", firstName: "Tharupahan", lastName: "Jayawardana", email: "tharupahanj.23@cse.mrt.ac.lk" },
    { regNo: "230303M", firstName: "Didula", lastName: "Jeewandara", email: "didulaj.23@cse.mrt.ac.lk" },
    { regNo: "230304R", firstName: "Babijana", lastName: "Jegarashan", email: "babijanaj.23@cse.mrt.ac.lk" },
    { regNo: "230305V", firstName: "Jitharsanan", lastName: "Thiruketheeswaran", email: "jitharsanant.23@cse.mrt.ac.lk" },
    { regNo: "230310G", firstName: "Kajatheepan", lastName: "Perinpanathan", email: "kajatheepanp.23@cse.mrt.ac.lk" },
    { regNo: "230311K", firstName: "Nemith", lastName: "Kaluarachchi", email: "nemithk.23@cse.mrt.ac.lk" },
    { regNo: "230313T", firstName: "Kamsan", lastName: "Suntharalingam", email: "kamsans.23@cse.mrt.ac.lk" },
    { regNo: "230315C", firstName: "Teshan", lastName: "Kannangara", email: "teshank.23@cse.mrt.ac.lk" },
    { regNo: "230317J", firstName: "Sangeeth", lastName: "Kariyapperuma", email: "sangeethk.23@cse.mrt.ac.lk" },
    { regNo: "230320L", firstName: "Chalani", lastName: "Karunanayaka", email: "chalanik.23@cse.mrt.ac.lk" },
    { regNo: "230324D", firstName: "Shehara", lastName: "Karunarathna", email: "sheharak.23@cse.mrt.ac.lk" },
    { regNo: "230328T", firstName: "Dinuka", lastName: "Kavinda", email: "dinukakavinda.23@cse.mrt.ac.lk" },
    { regNo: "230331V", firstName: "Kavyanga", lastName: "Hathurusinghe", email: "kavyangah.23@cse.mrt.ac.lk" },
    { regNo: "230334H", firstName: "Dinuka", lastName: "Keshara", email: "dinukakeshara.23@cse.mrt.ac.lk" },
    { regNo: "230335L", firstName: "Khamshayan", lastName: "Rajeshwaran", email: "khamshayanr.23@cse.mrt.ac.lk" },
  ];

  // Part 3: Students 101-150
  const voters3 = [
    { regNo: "230336P", firstName: "Sonath", lastName: "Kirindage", email: "sonathk.23@cse.mrt.ac.lk" },
    { regNo: "230345R", firstName: "Krishnaprashanth", lastName: "Sivasanger", email: "krishnaprashanths.23@cse.mrt.ac.lk" },
    { regNo: "230346V", firstName: "Vihanga", lastName: "Nimsara", email: "vihangan.23@cse.mrt.ac.lk" },
    { regNo: "230349H", firstName: "Nadil", lastName: "Kulathunge", email: "nadilk.23@cse.mrt.ac.lk" },
    { regNo: "230350D", firstName: "Nimesh", lastName: "Kulatunga", email: "nimeshk.23@cse.mrt.ac.lk" },
    { regNo: "230354T", firstName: "Pamoth", lastName: "Kumarasinghe", email: "pamothk.23@cse.mrt.ac.lk" },
    { regNo: "230356C", firstName: "kumarasinghemp", lastName: "", email: "kumarasinghemp.23@cse.mrt.ac.lk" },
    { regNo: "230359M", firstName: "Himandhi", lastName: "Kuruppu", email: "himandhik.23@cse.mrt.ac.lk" },
    { regNo: "230361L", firstName: "Pasindu", lastName: "Lakmal", email: "pasindul.23@cse.mrt.ac.lk" },
    { regNo: "230365D", firstName: "kalana", lastName: "lakshan", email: "kalanal.23@cse.mrt.ac.lk" },
    { regNo: "230370M", firstName: "Lakshika", lastName: "Gobinath", email: "lakshikag.23@cse.mrt.ac.lk" },
    { regNo: "230373B", firstName: "lawanyakkhg", lastName: "", email: "lawanyakkhg.23@cse.mrt.ac.lk" },
    { regNo: "230374E", firstName: "Januda", lastName: "Lelwala", email: "janudal.23@cse.mrt.ac.lk" },
    { regNo: "230381X", firstName: "Rashmika", lastName: "Madaela", email: "rashmikam.23@cse.mrt.ac.lk" },
    { regNo: "230384J", firstName: "Deepthi", lastName: "Devindi", email: "deepthid.23@cse.mrt.ac.lk" },
    { regNo: "230387V", firstName: "Janith", lastName: "Mahanama", email: "janithm.23@cse.mrt.ac.lk" },
    { regNo: "230389E", firstName: "Hiruna", lastName: "Malavipathirana", email: "hirunam.23@cse.mrt.ac.lk" },
    { regNo: "230394N", firstName: "Hesandi", lastName: "Mallawarachchi", email: "hesandim.23@cse.mrt.ac.lk" },
    { regNo: "230402P", firstName: "Mathulan", lastName: "Shanmugam", email: "mathulans.23@cse.mrt.ac.lk" },
    { regNo: "230415H", firstName: "Nilum", lastName: "Mudaliarachchi", email: "nilumm.23@cse.mrt.ac.lk" },
    { regNo: "230424J", firstName: "Dinithi", lastName: "Navodya", email: "dinithin.23@cse.mrt.ac.lk" },
    { regNo: "230425M", firstName: "Ashini", lastName: "Kavindya", email: "ashinik.23@cse.mrt.ac.lk" },
    { regNo: "230427V", firstName: "Praveen", lastName: "Nawarathna", email: "praveenn.23@cse.mrt.ac.lk" },
    { regNo: "230428B", firstName: "Neelayadhakshi", lastName: "Priyadhakshan", email: "neelayadhakship.23@cse.mrt.ac.lk" },
    { regNo: "230429E", firstName: "Heshan", lastName: "Nethmina", email: "heshann.23@cse.mrt.ac.lk" },
    { regNo: "230432G", firstName: "Nathasha", lastName: "Nethmini", email: "nathashan.23@cse.mrt.ac.lk" },
    { regNo: "230435T", firstName: "Chamodh", lastName: "Nethsara", email: "chamodhn.23@cse.mrt.ac.lk" },
    { regNo: "230437C", firstName: "nidharshan", lastName: "Vigneshwaram", email: "nidharshanv.23@cse.mrt.ac.lk" },
    { regNo: "230451M", firstName: "Janidu", lastName: "Pabasara", email: "janidup.23@cse.mrt.ac.lk" },
    { regNo: "230452R", firstName: "Kusal", lastName: "Pabasara", email: "kusalp.23@cse.mrt.ac.lk" },
    { regNo: "230453V", firstName: "Hasaranga", lastName: "Padmasiri", email: "hasarangap.23@cse.mrt.ac.lk" },
    { regNo: "230455E", firstName: "Lasana", lastName: "Pahanga", email: "lasanap.23@cse.mrt.ac.lk" },
    { regNo: "230461T", firstName: "Kalana", lastName: "Pankaja", email: "kalanap.23@cse.mrt.ac.lk" },
    { regNo: "230465J", firstName: "Chanul", lastName: "Pathirana", email: "chanulp.23@cse.mrt.ac.lk" },
    { regNo: "230467R", firstName: "Ravindu", lastName: "Pathirana", email: "ravindup.23@cse.mrt.ac.lk" },
    { regNo: "230475N", firstName: "Tharusha", lastName: "Perera", email: "tharushap.23@cse.mrt.ac.lk" },
    { regNo: "230482H", firstName: "Teshan", lastName: "Perera", email: "teshanp.23@cse.mrt.ac.lk" },
    { regNo: "230490F", firstName: "Pirasanth", lastName: "Vaigunthanathan", email: "pirasanthv.23@cse.mrt.ac.lk" },
    { regNo: "230501T", firstName: "Ranga", lastName: "Priyadarshana", email: "rangap.23@cse.mrt.ac.lk" },
    { regNo: "230505J", firstName: "Abdul", lastName: "Rafi", email: "abdulr.23@cse.mrt.ac.lk" },
    { regNo: "230506M", firstName: "Rahim", lastName: "Iqbal", email: "rahimi.23@cse.mrt.ac.lk" },
    { regNo: "230510U", firstName: "Sakindu", lastName: "Rajapaksa", email: "sakindur.23@cse.mrt.ac.lk" },
    { regNo: "230514K", firstName: "Lekshan", lastName: "Rajapaksha", email: "lekshanr.23@cse.mrt.ac.lk" },
    { regNo: "230515N", firstName: "rajapakshatndw", lastName: "", email: "rajapakshatndw.23@cse.mrt.ac.lk" },
    { regNo: "230518C", firstName: "Kanes", lastName: "Rakeshan", email: "kanesr.23@cse.mrt.ac.lk" },
    { regNo: "230522H", firstName: "Dineth", lastName: "Ranasinghe", email: "dinethr.23@cse.mrt.ac.lk" },
    { regNo: "230524P", firstName: "Manuja", lastName: "Ranathunga", email: "manujar.23@cse.mrt.ac.lk" },
    { regNo: "230531J", firstName: "ranhiruugi", lastName: "", email: "ranhiruugi.23@cse.mrt.ac.lk" },
    { regNo: "230541N", firstName: "Sanjuna", lastName: "Rathnamalala", email: "sanjunar.23@cse.mrt.ac.lk" },
    { regNo: "230547M", firstName: "RAVI", lastName: "SHEHAN", email: "ravis.23@cse.mrt.ac.lk" },
  ];

  // Part 4: Students 151-200
  const voters4 = [
    { regNo: "230554G", firstName: "ruththiragayan", lastName: "sutharsan", email: "ruththiragayans.23@cse.mrt.ac.lk" },
    { regNo: "230555K", firstName: "Safrina", lastName: "Rauf", email: "safrinar.23@cse.mrt.ac.lk" },
    { regNo: "230556N", firstName: "Saheththiyan", lastName: "Sri Baskaran", email: "saheththiyans.23@cse.mrt.ac.lk" },
    { regNo: "230557T", firstName: "Sahithyan", lastName: "Kandathasan", email: "sahithyank.23@cse.mrt.ac.lk" },
    { regNo: "230559C", firstName: "Sajiv", lastName: "Rajh", email: "sajivr.23@cse.mrt.ac.lk" },
    { regNo: "230562E", firstName: "Sanuji", lastName: "Samarakoon", email: "sanujis.23@cse.mrt.ac.lk" },
    { regNo: "230571F", firstName: "isuru", lastName: "sampath", email: "isurus.23@cse.mrt.ac.lk" },
    { regNo: "230578H", firstName: "Nisal", lastName: "Sanjula", email: "nisals.23@cse.mrt.ac.lk" },
    { regNo: "230582N", firstName: "Saran", lastName: "Santhiran", email: "sarans.23@cse.mrt.ac.lk" },
    { regNo: "230592U", firstName: "Sathurshna", lastName: "Uthayakumar", email: "sathurshnau.23@cse.mrt.ac.lk" },
    { regNo: "230595G", firstName: "VIRAN", lastName: "SENANAYAKE", email: "virans.23@cse.mrt.ac.lk" },
    { regNo: "230600V", firstName: "Sahan", lastName: "Madushanka", email: "sahanm.23@cse.mrt.ac.lk" },
    { regNo: "230601B", firstName: "Sithija", lastName: "Seneviratne", email: "sithijas.23@cse.mrt.ac.lk" },
    { regNo: "230602E", firstName: "Buwaneka", lastName: "Halpage", email: "buwanekah.23@cse.mrt.ac.lk" },
    { regNo: "230606U", firstName: "Shakeel", lastName: "Mohamed", email: "shakeelm.23@cse.mrt.ac.lk" },
    { regNo: "230607A", firstName: "Sarjana", lastName: "Shanmugarajah", email: "sarjanas.23@cse.mrt.ac.lk" },
    { regNo: "230611F", firstName: "Shazan", lastName: "Shaheed", email: "shazans.23@cse.mrt.ac.lk" },
    { regNo: "230615V", firstName: "Nishakya", lastName: "Silva", email: "nishakyas.23@cse.mrt.ac.lk" },
    { regNo: "230616B", firstName: "Dewni", lastName: "Silva", email: "dewnis.23@cse.mrt.ac.lk" },
    { regNo: "230621K", firstName: "Ajan", lastName: "Somarathna", email: "ajans.23@cse.mrt.ac.lk" },
    { regNo: "230623T", firstName: "Sriyathurshan", lastName: "Kovindarajah", email: "sriyathurshank.23@cse.mrt.ac.lk" },
    { regNo: "230626F", firstName: "Buvindu", lastName: "Suraweera", email: "buvindus.23@cse.mrt.ac.lk" },
    { regNo: "230631P", firstName: "lakmana", lastName: "thabrew", email: "lakmanat.23@cse.mrt.ac.lk" },
    { regNo: "230633A", firstName: "Thadshakan", lastName: "Jegatheeswaran", email: "thadshakanj.23@cse.mrt.ac.lk" },
    { regNo: "230642B", firstName: "Savindu", lastName: "Suranjith", email: "savindus.23@cse.mrt.ac.lk" },
    { regNo: "230647U", firstName: "Thilakshan", lastName: "Balakrishnan", email: "thilakshanb.23@cse.mrt.ac.lk" },
    { regNo: "230651C", firstName: "Maleesha", lastName: "Udayanga", email: "maleeshau.23@cse.mrt.ac.lk" },
    { regNo: "230653J", firstName: "Bimsara", lastName: "Udurawana", email: "bimsarau.23@cse.mrt.ac.lk" },
    { regNo: "230662K", firstName: "sanka", lastName: "vidanagama", email: "sankav.23@cse.mrt.ac.lk" },
    { regNo: "230665X", firstName: "Sandaru", lastName: "Vidushan", email: "sandaruv.23@cse.mrt.ac.lk" },
    { regNo: "230667F", firstName: "Virusan", lastName: "Thavanathan", email: "virusant.23@cse.mrt.ac.lk" },
    { regNo: "230670H", firstName: "Janith", lastName: "Vishula", email: "janithv.23@cse.mrt.ac.lk" },
    { regNo: "230674A", firstName: "rashmi", lastName: "paboda", email: "rashmip.23@cse.mrt.ac.lk" },
    { regNo: "230677K", firstName: "Sudil", lastName: "Waduge", email: "sudilw.23@cse.mrt.ac.lk" },
    { regNo: "230678N", firstName: "Pankaja", lastName: "Waidyasekara", email: "pankajaw.23@cse.mrt.ac.lk" },
    { regNo: "230682V", firstName: "Ranudula", lastName: "Wanniarachchi", email: "ranudulaw.23@cse.mrt.ac.lk" },
    { regNo: "230684E", firstName: "Januli", lastName: "Wansandi", email: "januliw.23@cse.mrt.ac.lk" },
    { regNo: "230694J", firstName: "Ranuga", lastName: "Weerasekara", email: "ranugaw.23@cse.mrt.ac.lk" },
    { regNo: "230696R", firstName: "Dulip", lastName: "Jayashanka", email: "dulipj.23@cse.mrt.ac.lk" },
    { regNo: "230699E", firstName: "Milindu", lastName: "Weerawarna", email: "milinduw.23@cse.mrt.ac.lk" },
    { regNo: "230701G", firstName: "Vinma", lastName: "Wettasinghe", email: "vinmaw.23@cse.mrt.ac.lk" },
    { regNo: "230702K", firstName: "Ashen", lastName: "Umeda", email: "ashenu.23@cse.mrt.ac.lk" },
    { regNo: "230703N", firstName: "Sineth", lastName: "Wickramaratna", email: "sinethw.23@cse.mrt.ac.lk" },
    { regNo: "230704T", firstName: "Anupama", lastName: "Wickramaratne", email: "anupamaw.23@cse.mrt.ac.lk" },
    { regNo: "230714A", firstName: "Oshadha", lastName: "Wijayarathne", email: "oshadhaw.23@cse.mrt.ac.lk" },
    { regNo: "230717K", firstName: "Thimalka", lastName: "Wijepala", email: "thimalkaw.23@cse.mrt.ac.lk" },
    { regNo: "230722V", firstName: "Senilka", lastName: "Madurapperumage", email: "senilkam.23@cse.mrt.ac.lk" },
    { regNo: "230725H", firstName: "Dehan", lastName: "Wijesinghe", email: "dehanw.23@cse.mrt.ac.lk" },
    { regNo: "230734J", firstName: "Sandenie", lastName: "Withana", email: "sandeniew.23@cse.mrt.ac.lk" },
    { regNo: "230736R", firstName: "Manushan", lastName: "Withanage", email: "manushanw.23@cse.mrt.ac.lk" },
  ];

  const allVoters = [...voters1, ...voters2, ...voters3, ...voters4];

  let count = 0;
  for (const v of allVoters) {
    await prisma.voterRegistry.upsert({
      where: { email: v.email },
      update: {
        regNo: v.regNo,
        firstName: normalizeName(v.firstName),
        lastName: normalizeName(v.lastName),
        indexNumber: v.regNo,
        isActive: true,
      },
      create: {
        regNo: v.regNo,
        email: v.email,
        firstName: normalizeName(v.firstName),
        lastName: normalizeName(v.lastName),
        indexNumber: v.regNo,
        isActive: true,
      },
    });
    count++;
  }

  console.log(`✅ Seeded ${count} voters from CSE 23 batch`);
}

main()
  .catch((e) => {
    console.error(e);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
